export const blogPosts = [
  {
    slug: 'rag-pipeline-architecture-guide',
    title: 'RAG Pipeline Architecture Guide: From Document Ingestion to AI-Generated Answers',
    description: 'A complete guide to building production RAG pipelines — semantic chunking, vector stores, hybrid retrieval strategies, and LLM integration by Ganapathi Ramkumar Palanivelu.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '8 min read',
    tags: ['RAG', 'Architecture', 'LangChain', 'Pinecone', 'LLM', 'GenAI'],
    sections: [
      { type: 'p', text: 'Retrieval-Augmented Generation (RAG) has emerged as the dominant architecture pattern for enterprise AI systems that need to combine the reasoning power of large language models with access to proprietary, real-time, or domain-specific knowledge. Unlike fine-tuning, RAG does not require retraining the model — it retrieves relevant context at query time and grounds the LLM response in that evidence.' },
      { type: 'h2', text: 'What is RAG and Why Does It Matter?' },
      { type: 'p', text: 'A RAG pipeline augments an LLM\'s response generation by first retrieving relevant documents from a knowledge base, then passing them as context to the model. This architecture delivers three critical benefits for enterprise AI:' },
      { type: 'ul', items: [
        'Grounded, verifiable responses backed by source documents with citations',
        'Dramatically reduced hallucination — the model answers from evidence, not parametric memory',
        'Dynamic knowledge updates without retraining — add new documents to the vector store and the system immediately has access to them',
        'Transparency and auditability — users can inspect the retrieved sources behind every answer',
      ]},
      { type: 'h2', text: 'The Five Stages of a Production RAG Pipeline' },
      { type: 'h3', text: '1. Document Ingestion' },
      { type: 'p', text: 'The pipeline begins with loading and parsing source documents. Enterprise systems typically ingest PDFs, Word documents, HTML pages, database exports, and API responses. Tools like LangChain\'s document loaders, LlamaIndex readers, and Unstructured.io handle heterogeneous formats. Key considerations: preserve document metadata (source, date, author) as it enables powerful filtering at retrieval time.' },
      { type: 'h3', text: '2. Semantic Chunking' },
      { type: 'p', text: 'Raw documents must be split into chunks small enough for the embedding model\'s context window but large enough to preserve semantic coherence. Fixed-size chunking (512–1024 tokens with 10–20% overlap) is the baseline. Semantic chunking — splitting at sentence or paragraph boundaries detected by an NLP model — delivers significantly better retrieval quality. For structured documents, hierarchical chunking preserves parent-child relationships between sections and their contents.' },
      { type: 'h3', text: '3. Embedding Generation' },
      { type: 'p', text: 'Each chunk is converted to a dense vector representation using an embedding model. OpenAI\'s text-embedding-3-large (3072 dimensions) delivers best-in-class retrieval quality. For cost-sensitive deployments, BGE-large-en-v1.5 (an open-source model) provides competitive performance. Embedding models must be chosen to match the language and domain of your documents — a general-purpose model underperforms on highly technical or domain-specific corpora.' },
      { type: 'h3', text: '4. Vector Store Integration' },
      { type: 'p', text: 'Chunk embeddings are stored in a vector database that enables fast approximate nearest-neighbour (ANN) search. The main options each have distinct trade-offs:' },
      { type: 'table', headers: ['Vector Store', 'Best For', 'Hosted', 'Key Feature'],
        rows: [
          ['Pinecone', 'Cloud-native, high scale', 'Yes (managed)', 'Metadata filtering, namespaces'],
          ['pgvector', 'Existing PostgreSQL stack', 'Self-hosted / RDS', 'SQL joins with vector search'],
          ['Chroma', 'Local dev and prototyping', 'Self-hosted', 'Zero-config setup'],
          ['Weaviate', 'Multi-modal, hybrid search', 'Managed or self', 'Built-in BM25 + vector hybrid'],
        ]
      },
      { type: 'h3', text: '5. Retrieval and Response Generation' },
      { type: 'p', text: 'At query time, the user\'s question is embedded and compared against stored chunk vectors using cosine similarity or dot product. The top-k most relevant chunks are retrieved and injected into the LLM prompt as context. For enterprise accuracy, pure dense retrieval is rarely sufficient — hybrid search combining dense vectors with BM25 keyword matching (using Reciprocal Rank Fusion to merge scores) consistently outperforms either method alone.' },
      { type: 'h2', text: 'Advanced RAG Patterns' },
      { type: 'ul', items: [
        'Re-ranking: Use a cross-encoder (e.g., Cohere Rerank, BGE-reranker) to re-score the top-k retrieved chunks for higher precision before generation.',
        'HyDE (Hypothetical Document Embeddings): Generate a hypothetical answer to the query, embed it, and use that vector for retrieval — significantly improves recall for complex questions.',
        'Query decomposition: Break multi-part questions into sub-queries, retrieve for each, then synthesise a combined answer.',
        'Self-RAG: The model evaluates its own retrieved context and decides whether to use it, regenerate, or answer from parametric memory.',
      ]},
      { type: 'h2', text: 'RAG Evaluation: Measuring What Matters' },
      { type: 'p', text: 'Evaluation is the most under-invested area in enterprise RAG deployments. The Ragas framework provides four essential metrics: Faithfulness (does the answer match the retrieved context?), Answer Relevancy (does the answer address the question?), Context Precision (are retrieved chunks relevant?), and Context Recall (are all relevant chunks retrieved?). LangSmith, Arize, and DeepEval provide production observability dashboards.' },
      { type: 'h2', text: 'Key Takeaways' },
      { type: 'ul', items: [
        'Start with semantic chunking over fixed-size — it improves retrieval quality significantly.',
        'Implement hybrid search (dense + BM25) from the beginning — it is almost always better than pure vector search.',
        'Preserve document metadata and use metadata filters to constrain retrieval scope.',
        'Build evaluation pipelines before going to production — Ragas + LangSmith is the standard stack.',
        'Re-ranking with a cross-encoder is a low-cost, high-impact improvement for any RAG system.',
      ]},
    ],
  },
  {
    slug: 'genai-vs-rag-enterprise-guide',
    title: 'GenAI vs RAG: Which Approach is Right for Your Enterprise AI Strategy?',
    description: 'Understand the fundamental difference between Generative AI and RAG, and learn a practical decision framework for choosing the right approach for your enterprise use case.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '7 min read',
    tags: ['GenAI', 'RAG', 'Enterprise AI', 'LLM', 'AI Strategy'],
    sections: [
      { type: 'p', text: 'One of the most common questions from enterprise architecture teams is: "Should we use Generative AI or RAG for this use case?" The answer depends entirely on your data, latency requirements, accuracy demands, and the nature of the task. This guide breaks down both approaches and provides a practical decision framework.' },
      { type: 'h2', text: 'What is Pure Generative AI?' },
      { type: 'p', text: 'Pure Generative AI (GenAI) refers to using a pre-trained or fine-tuned LLM directly — feeding a prompt and receiving generated text without any external retrieval step. The model answers from its parametric memory: knowledge encoded in its weights during training. This approach excels at creative tasks, code generation, summarisation of provided text, and general reasoning where the required knowledge was in the training data.' },
      { type: 'h2', text: 'What is RAG?' },
      { type: 'p', text: 'Retrieval-Augmented Generation augments the LLM with a retrieval step — relevant documents are fetched from a knowledge base and injected into the prompt before generation. The model reasons over the retrieved context rather than relying solely on parametric memory. This approach is essential whenever your use case requires up-to-date information, proprietary data, or high-stakes factual accuracy.' },
      { type: 'h2', text: 'Head-to-Head Comparison' },
      { type: 'table', headers: ['Dimension', 'Pure GenAI', 'RAG'],
        rows: [
          ['Knowledge currency', 'Training cutoff date', 'Real-time — updates instantly'],
          ['Factual accuracy', 'Can hallucinate confidently', 'Grounded in retrieved evidence'],
          ['Proprietary data', 'Requires fine-tuning', 'Native — index any document'],
          ['Explainability', 'Black box', 'Cites sources from retrieval'],
          ['Latency', 'Low (single LLM call)', 'Higher (retrieval + LLM)'],
          ['Cost', 'Low per query', 'Higher (embedding + vector DB)'],
          ['Setup complexity', 'Minimal', 'Significant infrastructure'],
          ['Best for', 'Creative, general tasks', 'Factual, domain-specific Q&A'],
        ]
      },
      { type: 'h2', text: 'When to Use Pure GenAI' },
      { type: 'ul', items: [
        'Creative content generation: marketing copy, product descriptions, code scaffolding',
        'Summarisation of text you provide in the prompt (no external retrieval needed)',
        'General reasoning, brainstorming, or ideation tasks',
        'Latency-critical applications where the extra retrieval step is unacceptable',
        'Tasks where all required knowledge was in the model\'s training data',
      ]},
      { type: 'h2', text: 'When to Use RAG' },
      { type: 'ul', items: [
        'Enterprise Q&A over internal documents, policies, contracts, or knowledge bases',
        'Customer support systems that must answer from product documentation',
        'Legal, compliance, or medical applications where factual grounding is critical',
        'Any system that needs knowledge more recent than the model\'s training cutoff',
        'Applications where you must provide citations and source references',
        'Regulatory environments that require explainable, auditable AI responses',
      ]},
      { type: 'h2', text: 'The Hybrid Approach: GenAI + RAG' },
      { type: 'p', text: 'Production enterprise AI systems rarely use one approach exclusively. The most powerful architecture combines both: RAG handles factual retrieval and grounding, while the LLM performs reasoning, synthesis, and generation over the retrieved context. Routing logic — a classifier or LLM-based query router — directs queries to RAG (factual questions) or pure generation (creative/reasoning tasks) based on query intent.' },
      { type: 'h2', text: 'Enterprise Decision Framework' },
      { type: 'ol', items: [
        'Does the task require knowledge not in the LLM training data? → RAG',
        'Does the task require proprietary, confidential, or real-time data? → RAG',
        'Is factual accuracy and auditability critical? → RAG',
        'Is the task primarily creative, generative, or reasoning-based? → Pure GenAI',
        'Do you need sub-200ms latency? → Pure GenAI or cached RAG',
        'Is the task a mix of factual and creative? → Hybrid RAG + GenAI with a query router',
      ]},
    ],
  },
  {
    slug: 'multi-agent-ai-design-patterns',
    title: 'Multi-Agent AI Systems: Design Patterns for Enterprise Production',
    description: 'Learn the key design patterns for building production-grade multi-agent AI systems — orchestration strategies, tool use, observability, and frameworks including LangGraph and CrewAI.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '9 min read',
    tags: ['Multi-Agent AI', 'LangGraph', 'CrewAI', 'AI Architecture', 'Agentic AI'],
    sections: [
      { type: 'p', text: 'Multi-agent AI systems — where multiple specialised AI agents collaborate to complete complex tasks — represent the next frontier of enterprise AI architecture. Unlike single-agent systems, multi-agent designs enable parallelisation, specialisation, and iterative refinement. However, they introduce significant complexity in orchestration, observability, and failure handling.' },
      { type: 'h2', text: 'What is a Multi-Agent AI System?' },
      { type: 'p', text: 'A multi-agent system (MAS) consists of multiple LLM-powered agents, each with a specific role, set of tools, and decision scope. Agents communicate via message passing or shared memory. An orchestrator (which may itself be an LLM) directs the workflow, delegates sub-tasks to specialist agents, and synthesises their outputs into a final result.' },
      { type: 'h2', text: 'Core Agent Components' },
      { type: 'ul', items: [
        'Brain (LLM): The reasoning engine — typically GPT-4, Claude Opus, or a domain-specific fine-tuned model.',
        'Memory: Short-term (conversation context window), long-term (vector store retrieval), and episodic (structured log of past actions).',
        'Tools: Function-call APIs the agent can invoke — web search, code execution, database queries, file I/O, external APIs.',
        'Planning: The strategy for decomposing a goal into a sequence of actions (ReAct, CoT, Tree-of-Thought).',
        'Action: Executing a chosen tool and processing the result.',
      ]},
      { type: 'h2', text: 'Three Core Orchestration Patterns' },
      { type: 'h3', text: 'Pattern 1: Sequential Pipeline' },
      { type: 'p', text: 'Agents execute in a fixed sequence: Agent A produces output → Agent B consumes it → Agent C refines the result. Simple to reason about, easy to debug, but no parallelism. Best for: document processing workflows where each stage depends on the previous (e.g., extract → summarise → classify → route).' },
      { type: 'h3', text: 'Pattern 2: Parallel Fan-Out / Fan-In' },
      { type: 'p', text: 'The orchestrator spawns multiple agents simultaneously, each handling a different sub-task or data partition. Results are aggregated (fan-in) and synthesised. Dramatically reduces wall-clock latency for independent tasks. Best for: research tasks requiring multiple information sources, batch document processing, or A/B evaluation of multiple LLM responses.' },
      { type: 'h3', text: 'Pattern 3: Hierarchical with Reflection' },
      { type: 'p', text: 'A supervisor agent delegates to worker agents, then a critic/reviewer agent evaluates the output and feeds corrections back — creating an iterative refinement loop. This pattern produces the highest quality outputs but is the most expensive. Best for: code generation with self-debugging, research report writing, or any task where quality matters more than cost.' },
      { type: 'h2', text: 'Framework Comparison' },
      { type: 'table', headers: ['Framework', 'Paradigm', 'Key Strength', 'Best For'],
        rows: [
          ['LangGraph', 'Stateful graph execution', 'Fine-grained control, persistent state', 'Complex, production workflows'],
          ['CrewAI', 'Role-based crew abstraction', 'Fast prototyping, readable definitions', 'Collaborative agent teams'],
          ['AutoGen', 'Conversational agents', 'Easy multi-agent dialogue', 'Research and experimentation'],
          ['Semantic Kernel', 'Plugin-based orchestration', 'Microsoft ecosystem integration', 'Enterprise Azure deployments'],
        ]
      },
      { type: 'h2', text: 'Tool Use and Model Context Protocol (MCP)' },
      { type: 'p', text: 'Anthropic\'s Model Context Protocol (MCP) is becoming the standard interface for connecting agents to external tools and data sources. MCP provides a standardised way for agents to discover and invoke tools — analogous to USB-C for AI integrations. Enterprise implementations should build tool registries with MCP-compatible interfaces to enable seamless agent-tool connectivity across the organisation.' },
      { type: 'h2', text: 'Production Considerations' },
      { type: 'ul', items: [
        'Observability: Use LangSmith, Arize Phoenix, or Weights & Biases to trace every agent call, tool invocation, and token spend.',
        'Cost control: Multi-agent workflows can burn tokens rapidly. Implement per-workflow token budgets and route sub-tasks to cheaper models where appropriate.',
        'Failure handling: Design for graceful degradation — if a sub-agent fails, the orchestrator should retry, fall back, or surface the error gracefully rather than silently producing wrong output.',
        'Human-in-the-loop: For high-stakes decisions, checkpoint workflows at critical decision points for human review before proceeding.',
        'Determinism: Add structured output schemas (JSON mode) to prevent agents from producing unparseable results that break downstream agents.',
      ]},
    ],
  },
  {
    slug: 'enterprise-architecture-ai-togaf',
    title: 'Applying TOGAF to Enterprise AI: Architecture Framework for GenAI Systems',
    description: 'How to apply TOGAF enterprise architecture principles to design scalable, governed, and business-aligned GenAI systems — from business architecture through technology architecture.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '8 min read',
    tags: ['TOGAF', 'Enterprise Architecture', 'AI Architecture', 'GenAI', 'Cloud Architecture'],
    sections: [
      { type: 'p', text: 'Most enterprise AI initiatives fail not because of technology limitations, but because of architecture gaps — misalignment between AI capabilities and business outcomes, ungoverned data estates, and technology platforms that can\'t scale. TOGAF\'s Architecture Development Method (ADM) provides a disciplined framework for closing these gaps. This article shows how to apply it specifically to GenAI programmes.' },
      { type: 'h2', text: 'Why Enterprise AI Needs an Architecture Framework' },
      { type: 'p', text: 'GenAI introduces new architectural concerns that traditional EA frameworks weren\'t designed for: model governance and responsible AI, non-deterministic behaviour, prompt engineering as a first-class artefact, vector stores as a new data tier, and the economics of inference at scale. TOGAF, extended with AI-specific architecture building blocks, provides the rigour that pure ML engineering approaches lack.' },
      { type: 'h2', text: 'Business Architecture: Aligning AI to Outcomes' },
      { type: 'p', text: 'The TOGAF ADM Phase A (Architecture Vision) mandates defining the business context before any technology decision. For GenAI, this means mapping AI capabilities to specific business capabilities and outcomes. Avoid the common trap of deploying AI solutions in search of problems. For each proposed AI use case, document: the business capability it enhances, the measurable KPI it improves, the data it requires, and the risk it introduces.' },
      { type: 'h2', text: 'Data Architecture: The AI Data Estate' },
      { type: 'p', text: 'TOGAF Phase C (Information Systems Architecture) covers data architecture. For AI systems, the data estate must be extended to include a vector tier alongside the traditional operational and analytical tiers. Key components: a document ingestion layer (handling PDFs, databases, APIs), an embedding pipeline, a vector store with metadata indexing, and a lineage system that tracks which source documents contributed to which AI responses. Data governance for AI means knowing where every training or retrieval document came from.' },
      { type: 'h2', text: 'Application Architecture: AI Platform Layers' },
      { type: 'p', text: 'The AI application layer follows a standard four-tier pattern that maps cleanly to TOGAF application architecture artefacts:' },
      { type: 'ol', items: [
        'Model Services Layer: LLM API integrations (Azure OpenAI, AWS Bedrock, Groq) with unified interface abstraction, model routing, and fallback chains.',
        'Orchestration Layer: LangChain / LangGraph / Semantic Kernel for RAG pipelines, agent workflows, and tool execution.',
        'API Gateway Layer: FastAPI or Kong for rate limiting, authentication, usage metering, and prompt injection protection.',
        'Application Layer: Domain-specific AI applications (document Q&A, code assistant, customer support bot) consuming the platform services.',
      ]},
      { type: 'h2', text: 'Technology Architecture: Multi-Cloud AI Infrastructure' },
      { type: 'p', text: 'TOGAF Phase D (Technology Architecture) maps application components to technology platforms. For enterprise AI, the key technology decisions are: primary cloud provider for AI services (Azure vs. AWS vs. GCP), vector database (managed vs. self-hosted), compute for inference (serverless vs. dedicated GPU), and observability stack. A multi-cloud AI strategy avoids model vendor lock-in — use Azure OpenAI for GPT-4 while maintaining the ability to route to AWS Bedrock\'s Claude or self-hosted Ollama.' },
      { type: 'h2', text: 'AI Governance and Responsible AI Architecture' },
      { type: 'p', text: 'The TOGAF Architecture Governance framework maps directly to AI governance requirements. Key governance artefacts for AI: an AI Use Case Registry (approved use cases with risk ratings), a Model Access Policy (who can call which models, with what data), an Audit Log Architecture (immutable logs of all prompts, retrievals, and responses), and a Responsible AI Review Board that evaluates new AI use cases against ethics and compliance criteria.' },
      { type: 'h2', text: 'Key Takeaways' },
      { type: 'ul', items: [
        'Start with business architecture — map AI capabilities to measurable business outcomes before selecting technology.',
        'Treat the vector tier as a first-class data architecture component alongside your operational and analytical databases.',
        'Design the AI platform in four layers: model services, orchestration, API gateway, and domain applications.',
        'Build governance from the start — an AI Use Case Registry and Audit Log are non-negotiable for enterprise deployments.',
        'TOGAF\'s ADM is a cycle, not a waterfall — revisit and refine architecture decisions as AI capabilities evolve rapidly.',
      ]},
    ],
  },
  {
    slug: 'llm-evaluation-production',
    title: 'LLM Evaluation: How to Measure AI Quality in Production',
    description: 'A practical guide to evaluating LLM and RAG systems in production — metrics, frameworks, automated pipelines, and the key signals that tell you when your AI is failing.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '7 min read',
    tags: ['LLM', 'Evaluation', 'RAG', 'MLOps', 'Ragas', 'LangSmith'],
    sections: [
      { type: 'p', text: 'Most enterprise AI projects deploy without a proper evaluation framework, then discover quality problems in production from user complaints. Building evaluation into your development and deployment pipeline from the beginning is the single most important practice that separates production-grade AI systems from prototypes.' },
      { type: 'h2', text: 'Why LLM Evaluation is Different from Traditional Software Testing' },
      { type: 'p', text: 'Traditional software testing is deterministic — given input X, the system must produce output Y. LLM outputs are probabilistic and contextual. A response can be factually correct, well-formatted, and still fail to answer the actual question. Evaluation requires measuring dimensions that have no direct parallel in traditional software: faithfulness, relevance, coherence, and groundedness.' },
      { type: 'h2', text: 'The Four Core RAG Evaluation Metrics' },
      { type: 'table', headers: ['Metric', 'Measures', 'Ideal Value', 'Bad Sign'],
        rows: [
          ['Faithfulness', 'Does the answer match the retrieved context?', '>0.9', '<0.7 → hallucination risk'],
          ['Answer Relevancy', 'Does the answer address the question?', '>0.85', '<0.7 → off-topic responses'],
          ['Context Precision', 'Are retrieved chunks relevant?', '>0.8', '<0.6 → poor retrieval'],
          ['Context Recall', 'Was all relevant info retrieved?', '>0.75', '<0.5 → missing key context'],
        ]
      },
      { type: 'h2', text: 'Component-Level vs End-to-End Evaluation' },
      { type: 'p', text: 'Evaluate both the retrieval component and the generation component independently before measuring the full pipeline. A low end-to-end score is hard to debug without knowing whether the problem is in retrieval (wrong chunks) or generation (wrong reasoning over correct chunks). Use retrieval-only metrics (NDCG, MRR, Recall@k) to evaluate the vector store, and generation-only metrics (faithfulness, answer relevancy) to evaluate the LLM.' },
      { type: 'h2', text: 'Automated Evaluation with Ragas' },
      { type: 'code', lang: 'python', text: `from ragas import evaluate
from ragas.metrics import (
    faithfulness, answer_relevancy,
    context_precision, context_recall,
    answer_correctness,
)
from datasets import Dataset

test_data = {
    "question":   ["What is RAG?", "How does semantic chunking work?"],
    "answer":     ["RAG is retrieval-augmented generation...", "Semantic chunking splits at sentence boundaries..."],
    "contexts":   [["RAG combines LLM with retrieval..."], ["Chunking strategies include fixed-size..."]],
    "ground_truth": ["Retrieval-Augmented Generation combines...", "Semantic chunking preserves natural language boundaries..."],
}

dataset = Dataset.from_dict(test_data)
results = evaluate(
    dataset,
    metrics=[faithfulness, answer_relevancy, context_precision, context_recall, answer_correctness],
)
print(results)
# Output: {'faithfulness': 0.92, 'answer_relevancy': 0.88, ...}` },
      { type: 'h2', text: 'LLM-as-a-Judge for Qualitative Evaluation' },
      { type: 'p', text: 'For dimensions that are hard to measure automatically (tone, completeness, helpfulness), use a stronger LLM (GPT-4o) as an evaluator. Present the original question, the context, and the generated answer, then ask the judge LLM to score on a 1–5 scale with reasoning. This "LLM-as-a-Judge" approach correlates well with human evaluation at a fraction of the cost and enables automated regression testing.' },
      { type: 'h2', text: 'Production Monitoring Signals' },
      { type: 'ul', items: [
        'Thumbs up/down feedback from users — the cheapest and most reliable signal of response quality.',
        'Retrieval latency percentiles (p50, p95, p99) — spikes indicate vector index degradation.',
        'Context window utilisation — responses where the context fills >80% of the window often have truncation issues.',
        'Refusal rate — if the LLM is refusing to answer or saying "I don\'t know" frequently, retrieval quality may have degraded.',
        'Token spend per query — unexpected spikes often indicate retrieval returning excessively long or irrelevant chunks.',
        'Answer length distribution — sudden changes in average answer length can signal prompt injection or model behaviour drift.',
      ]},
      { type: 'h2', text: 'Building a Regression Test Suite' },
      { type: 'p', text: 'Create a golden dataset of 50–100 question-answer pairs that represent your most important use cases. Run this suite automatically on every model, prompt, or retrieval configuration change. A CI/CD gate that blocks deployment if faithfulness drops below 0.85 or answer relevancy drops below 0.80 prevents quality regressions from reaching production undetected.' },
      { type: 'h2', text: 'Key Takeaways' },
      { type: 'ul', items: [
        'Measure retrieval and generation separately — a low end-to-end score needs component-level diagnosis.',
        'Faithfulness is your most important metric — it directly measures hallucination risk.',
        'Build a golden dataset of 50–100 Q&As and run it as a CI/CD gate on every change.',
        'LLM-as-a-Judge scales qualitative evaluation to hundreds of examples per hour.',
        'Production monitoring (user feedback, latency, refusal rate) is different from offline evaluation — you need both.',
      ]},
    ],
  },
  {
    slug: 'azure-openai-vs-aws-bedrock',
    title: 'Azure OpenAI vs AWS Bedrock: Choosing Your Enterprise AI Platform',
    description: 'A comprehensive comparison of Azure OpenAI Service and AWS Bedrock for enterprise AI deployments — model selection, security, pricing, integration, and a clear decision framework.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '8 min read',
    tags: ['Azure OpenAI', 'AWS Bedrock', 'Enterprise AI', 'Cloud', 'LLM', 'Architecture'],
    sections: [
      { type: 'p', text: 'For most enterprise AI initiatives, the first strategic decision is which cloud AI platform to build on. Azure OpenAI Service and AWS Bedrock are the two dominant enterprise offerings, and they make different trade-offs. This analysis is based on production deployments on both platforms.' },
      { type: 'h2', text: 'Platform Overview' },
      { type: 'p', text: 'Azure OpenAI Service provides exclusive access to OpenAI\'s models (GPT-4, GPT-4o, o1, DALL-E, Whisper) within the Azure security boundary — your data never leaves your Azure tenant and does not train OpenAI\'s models. AWS Bedrock is a multi-model platform providing access to models from Anthropic (Claude), Meta (Llama), Mistral, Cohere, Amazon (Titan), and others through a unified API with native AWS security integration.' },
      { type: 'h2', text: 'Model Availability' },
      { type: 'table', headers: ['Model Family', 'Azure OpenAI', 'AWS Bedrock'],
        rows: [
          ['GPT-4 / GPT-4o', '✅ Full access', '❌ Not available'],
          ['o1 / o3 reasoning', '✅ Available', '❌ Not available'],
          ['Claude (Anthropic)', '❌ Not available', '✅ Claude 3.5, 3, Haiku'],
          ['Llama (Meta)', '✅ Via Azure AI', '✅ Llama 3.x'],
          ['Mistral', '✅ Via Azure AI', '✅ Available'],
          ['Amazon Titan', '❌', '✅ Embeddings + generation'],
          ['Cohere', '❌', '✅ Command R+'],
          ['Stable Diffusion', '❌', '✅ Via Bedrock'],
        ]
      },
      { type: 'h2', text: 'Security and Compliance' },
      { type: 'p', text: 'Both platforms offer enterprise-grade security, but with different integration stories. Azure OpenAI integrates natively with Azure Active Directory (Entra ID), Azure Key Vault, Azure Private Link, and Azure Policy — ideal for Microsoft-first enterprises with existing Azure security posture. AWS Bedrock integrates with IAM, AWS KMS, AWS PrivateLink, and AWS CloudTrail, with VPC-native deployment — natural for AWS-native organisations.' },
      { type: 'ul', items: [
        'Data residency: Both offer regional deployments. Azure provides Sovereign Cloud (Azure Government, Azure China) options; AWS provides GovCloud.',
        'Data retention: Both commit to not training on customer API data. Azure provides an additional Data Processing Addendum.',
        'Model customisation: Azure OpenAI supports GPT-4 fine-tuning; AWS Bedrock supports fine-tuning for Claude, Llama, and Titan.',
        'Audit logging: Azure Monitor + Diagnostic Logs vs. AWS CloudTrail + CloudWatch — both comprehensive.',
      ]},
      { type: 'h2', text: 'Pricing Model' },
      { type: 'p', text: 'Both use per-token pricing. Azure OpenAI pricing mirrors OpenAI API pricing with regional variations. AWS Bedrock pricing varies by model — Claude 3.5 Sonnet is typically cheaper per token than GPT-4o for similar quality tasks. AWS Bedrock also offers Provisioned Throughput (reserved capacity) for consistent latency at high volume, equivalent to Azure OpenAI\'s Provisioned Deployments.' },
      { type: 'h2', text: 'Integration and Developer Experience' },
      { type: 'ul', items: [
        'SDKs: Azure OpenAI uses the OpenAI Python SDK with an Azure-specific client — code is largely compatible between OpenAI API and Azure OpenAI. AWS Bedrock uses boto3 with a distinct API — requires code changes to switch models.',
        'LangChain integration: Both have first-class LangChain integrations (ChatAzureOpenAI, BedrockChat). LlamaIndex also supports both.',
        'Embeddings: Azure OpenAI provides text-embedding-3-large/small. AWS Bedrock provides Amazon Titan Embeddings and Cohere Embed.',
        'Function calling / Tool use: Both support structured tool use. Azure follows OpenAI\'s function calling format; Bedrock follows Anthropic\'s tool use format for Claude.',
      ]},
      { type: 'h2', text: 'Decision Framework' },
      { type: 'ul', items: [
        'Choose Azure OpenAI if: you need GPT-4o / o1, you are Microsoft-first (M365, Azure AD, Teams), or your compliance team requires Microsoft\'s data processing agreements.',
        'Choose AWS Bedrock if: you are AWS-native, you need Claude (best reasoning for complex tasks), you want model diversity (multiple providers in one API), or you need lower per-token costs for high-volume use cases.',
        'Use both if: you need GPT-4o for some tasks and Claude for others — abstract your LLM client behind a routing layer (LiteLLM or a custom factory) for model-agnostic application code.',
      ]},
    ],
  },
  {
    slug: 'vector-database-design-patterns',
    title: 'Vector Database Architecture: Design Patterns for Production RAG',
    description: 'Essential vector database design patterns for enterprise RAG — indexing strategies, namespace design, metadata filtering, multi-tenancy, and scaling from prototype to production.',
    date: '2026-05-13',
    author: 'Ganapathi Ramkumar Palanivelu',
    readTime: '7 min read',
    tags: ['Vector Database', 'RAG', 'Architecture', 'Pinecone', 'pgvector', 'Design Patterns'],
    sections: [
      { type: 'p', text: 'Vector databases are the backbone of every RAG system, yet most teams treat them as a black box — insert documents, query by similarity, done. Production systems require deliberate design: namespace strategy, metadata schema, index configuration, and multi-tenancy patterns. Getting these wrong means rebuilding your entire data layer six months into production.' },
      { type: 'h2', text: 'Choosing Your Index Type' },
      { type: 'p', text: 'Most vector databases offer two index types with fundamentally different trade-offs:' },
      { type: 'table', headers: ['Index Type', 'Algorithm', 'Query Speed', 'Memory', 'Accuracy', 'Best For'],
        rows: [
          ['IVFFlat', 'Inverted file with flat quantisation', 'Fast', 'Low', 'Good (approximate)', 'Large datasets, cost-sensitive'],
          ['HNSW', 'Hierarchical Navigable Small World graphs', 'Fastest', 'High', 'Excellent', 'Low-latency production workloads'],
        ]
      },
      { type: 'p', text: 'For production RAG, use HNSW. The memory cost is justified by the latency and accuracy improvements. For pgvector: CREATE INDEX ON chunks USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64).' },
      { type: 'h2', text: 'Metadata Schema Design' },
      { type: 'p', text: 'Every chunk should carry metadata that enables filtering before or during similarity search. Design your metadata schema before ingestion — changing it later requires re-indexing all documents. Essential metadata fields for enterprise RAG:' },
      { type: 'ul', items: [
        'source_id: Unique identifier of the source document — enables document-level operations (update, delete).',
        'source_type: PDF, web, database, API — enables type-based filtering.',
        'created_at / updated_at: Timestamps for freshness filtering ("only use documents from the last 90 days").',
        'tenant_id / user_id: For multi-tenant systems — enables row-level security on retrieval.',
        'section / chapter: Document structure metadata for hierarchical retrieval.',
        'language: For multilingual corpora — filter to the user\'s language before retrieval.',
        'access_level: Public / internal / confidential — enforce document permissions at retrieval time.',
      ]},
      { type: 'h2', text: 'Multi-Tenancy Patterns' },
      { type: 'p', text: 'Enterprise RAG systems often serve multiple customers or departments from a single infrastructure. Three patterns exist, each with different isolation guarantees:' },
      { type: 'table', headers: ['Pattern', 'Isolation', 'Cost', 'Complexity', 'Best For'],
        rows: [
          ['Separate index per tenant', 'Complete', 'High', 'Medium', 'High-security, large enterprise tenants'],
          ['Namespace per tenant (Pinecone)', 'Index-level', 'Medium', 'Low', 'SaaS with many tenants'],
          ['Metadata filter per tenant', 'Query-level', 'Low', 'Lowest', 'Internal tools, trusted users'],
        ]
      },
      { type: 'h2', text: 'Document Update and Deletion' },
      { type: 'p', text: 'Handling document updates is a common production pain point. When a source document changes, you must delete all chunks from the old version and re-ingest the new version. Store the source_id in metadata and implement a two-step update: (1) delete all vectors WHERE source_id = X, (2) re-ingest the updated document. Without this, stale chunks accumulate and degrade retrieval quality over time.' },
      { type: 'code', lang: 'python', text: `def update_document(vector_store, source_id: str, new_pdf_path: str):
    # Step 1: Delete all existing chunks for this document
    vector_store.delete(filter={"source_id": source_id})

    # Step 2: Re-ingest the updated document
    chunks = load_and_chunk(new_pdf_path)
    for chunk in chunks:
        chunk.metadata["source_id"] = source_id
    vector_store.add_documents(chunks)
    print(f"Updated {len(chunks)} chunks for document {source_id}")` },
      { type: 'h2', text: 'Scaling from Prototype to Production' },
      { type: 'ul', items: [
        'Start with Chroma locally for development — zero setup, runs in-process.',
        'Move to pgvector (via Supabase or Railway) for staging — same SQL interface you\'ll use in production if you\'re PostgreSQL-native.',
        'For > 5M vectors or < 20ms p99 latency requirements, migrate to Pinecone or Weaviate managed services.',
        'Implement async ingestion from day one — synchronous ingestion during user requests blocks the API and doesn\'t scale.',
        'Monitor index size weekly — HNSW index performance degrades without periodic re-indexing when the corpus grows significantly.',
      ]},
    ],
  },
];
